config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root 'articles#index'
  resources :articles do
    resources :comments
  end

end

app/models/article.rb
class Article < ActiveRecord::Base
    validates :title, presence: true
    validates :body, presence: true
    
    belongs_to :user
    has_many :comments, dependent: :destroy
    
    default_scope {order(created_at: :desc)}
    
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
  belongs_to :user
  
  validates :body, presence: true
  
  def self.persisted
    where.not(id: nil)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_filter :set_article, only: [:edit, :update, :show, :destroy]
  
  
  def index
    @articles = Article.all
  end
  
  def new
    @article = Article.new
  end
  
  def create
    @article = current_user.articles.build(article_params)
    if @article.save
      flash[:success] = 'Article has been created'  
      redirect_to articles_path
    else
      flash.now[:danger] = "Article has not been created"
      render :new
    end
  end
  
  def edit
    if @article.user != current_user
      flash[:danger] = "You can only edit your own articles"
      redirect_to root_path
    end
  end
  
  def update
    if @article.user != current_user 
      flash[:danger] = "You can only edit your own articles"
      redirect_to root_path
    else
      if @article.update(article_params)
        flash[:success] = "Article has been updated"
        redirect_to @article
      else
        flash.now[:danger] = 'Article has not been updated'
        render :edit
      end
    end
  end
  
  
  def show
    @comment = @article.comments.build
  end
  
  def destroy
    
    
    if @article.destroy
      flash[:success] = "Article has been deleted"
      redirect_to articles_path
    end
    
  end
  
  
  
  
  
  private
  
    def article_params
      
      params.require(:article).permit(:title, :body)
      
    end
    
    def set_article
      @article = Article.find(params[:id])
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :set_article
    
    def create
        unless current_user
            flash[:danger] = "Please sign in or sign up first"
            redirect_to new_user_session_path
        else
            @comment = @article.comments.build(comment_params)
            @comment.user = current_user
            
            if @comment.save
               flash[:success] = 'Comment has been created'
            else
                flash.now[:danger] = 'Comment has not been created'
            end
            redirect_to article_path(@article)
        end
    end
    
    private
        def comment_params
            params.require(:comment).permit(:body)
        end
        
        def set_article
           @article = Article.find(params[:article_id]) 
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def devise_error_messages!
       return '' if resource.errors.empty?
       
       messages = resource.errors.full_messages.map {
           |msg| content_tag(:li, msg)
       }.join
       
       html = <<-HTML
        <div class='alert alert-error alert-danger>
            <a href='#' class='close', data-dismiss='alert' &#215;></a>
            <%= content_tag :div, msg if msg.is_a?(String) %>
        </div>
       HTML
       html.html_safe
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_form.html.erb
    <div class='row'>
         <div class='col-md-12'>
             <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
             <% if @article.errors.any? %>
                 <div class='panel panel-danger col-md-offset-1'>
                     <div class='panel-heading'>
                         <h2 class='panel-title'>
                            <%= pluralize(@article.errors.count, "error") %>
                             prohibited this article from being saved 
                         </h2>
                         <div class='panel-body'>
                             <ul>
                                 <% @article.errors.full_messages.each do |msg| %>
                                     <li><%= msg %></li>
                                 <% end %>
                             </ul>
                         </div>
                     </div>
                 </div>
             <% end %>
                 <div class='form-group'>
                     <div class='control-label col-md-1'>
                         <%= f.label :title %>
                     </div>
                     <div class='col-md-11'>
                         <%= f.text_field :title, class: 'form-control', placeholder: 'Title of article', autofocus: true %>
                     </div>
                 </div>
                 <div class='form-group'>
                     <div class='control-label col-md-1'>
                         <%= f.label :body %>
                     </div>
                     <div class='col-md-11'>
                         <%= f.text_area :body, rows: 10, class: 'form-control', placeholder: 'Body of article' %>
                     </div>
                 </div>
                 <div class='form-group'>
                     <div class='col-md-offset-1 col-md-11'>
                         <%= f.submit "Submit", class: 'btn btn-primary btn-lg pull-right' %>
                     </div>
                 </div>
             <% end %>
         </div>
    </div>

app/views/articles/edit.html.erb
<h3 class='text-center'> Editing an Article</h3>
    
<div class='row'>
         <div class='col-md-12'>
             <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
             <% if @article.errors.any? %>
                 <div class='panel panel-danger col-md-offset-1'>
                     <div class='panel-heading'>
                         <h2 class='panel-title'>
                            <%= pluralize(@article.errors.count, "error") %>
                             prohibited this article from being saved 
                         </h2>
                         <div class='panel-body'>
                             <ul>
                                 <% @article.errors.full_messages.each do |msg| %>
                                     <li><%= msg %></li>
                                 <% end %>
                             </ul>
                         </div>
                     </div>
                 </div>
             <% end %>
                 <div class='form-group'>
                     <div class='control-label col-md-1'>
                         <%= f.label :title %>
                     </div>
                     <div class='col-md-11'>
                         <%= f.text_field :title, class: 'form-control', placeholder: 'Title of article', autofocus: true %>
                     </div>
                 </div>
                 <div class='form-group'>
                     <div class='control-label col-md-1'>
                         <%= f.label :body %>
                     </div>
                     <div class='col-md-11'>
                         <%= f.text_area :body, rows: 10, class: 'form-control', placeholder: 'Body of article' %>
                     </div>
                 </div>
                 <div class='form-group'>
                     <div class='col-md-offset-1 col-md-11'>
                         <%= f.submit "Update Article", class: 'btn btn-primary btn-lg pull-right' %>
                     </div>
                 </div>
             <% end %>
         </div>
    </div>

app/views/articles/index.html.erb
<h1>Listing all Article</h1>
<% if user_signed_in? %>
    <%= link_to "New Article", new_article_path, class: 'btn btn-default btn-lg', id: 'new-article-btn' %>
<% end %>

<% @articles.each do |article| %>
    <div class='well well-lg'>
        <div class='article-title'>
            <%= link_to article.title, article_path(article) %>
        </div>
        <div class='article-body'>
            <%= truncate(article.body, length: 500) %>
        </div>
        <div class='author'>
            <% if article.user %>
                <small>Created by: <%= article.user.email %></small>
            <% end %>
        </div>
    </div>

<% end %>

app/views/articles/new.html.erb
<h3 class='text-center'> Adding New Article</h3>

<div class='row'>
         <div class='col-md-12'>
             <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
             <% if @article.errors.any? %>
                 <div class='panel panel-danger col-md-offset-1'>
                     <div class='panel-heading'>
                         <h2 class='panel-title'>
                            <%= pluralize(@article.errors.count, "error") %>
                             prohibited this article from being saved 
                         </h2>
                         <div class='panel-body'>
                             <ul>
                                 <% @article.errors.full_messages.each do |msg| %>
                                     <li><%= msg %></li>
                                 <% end %>
                             </ul>
                         </div>
                     </div>
                 </div>
             <% end %>
                 <div class='form-group'>
                     <div class='control-label col-md-1'>
                         <%= f.label :title %>
                     </div>
                     <div class='col-md-11'>
                         <%= f.text_field :title, class: 'form-control', placeholder: 'Title of article', autofocus: true %>
                     </div>
                 </div>
                 <div class='form-group'>
                     <div class='control-label col-md-1'>
                         <%= f.label :body %>
                     </div>
                     <div class='col-md-11'>
                         <%= f.text_area :body, rows: 10, class: 'form-control', placeholder: 'Body of article' %>
                     </div>
                 </div>
                 <div class='form-group'>
                     <div class='col-md-offset-1 col-md-11'>
                         <%= f.submit "Create Article", class: 'btn btn-primary btn-lg pull-right' %>
                     </div>
                 </div>
             <% end %>
         </div>
    </div>

app/views/articles/show.html.erb
<article class='detail-article'>
    <h1 class='article-detail-title'><%= @article.title %></h1>
    
    <div class='glyphicon glyphicon-calendar' id='article-date'><%= @article.created_at.strftime("%b %d, %Y") %></div>
    
    <div class='article-body'>
        <%= @article.body %>
    </div>
    
    <% if user_signed_in? and current_user == @article.user %>
        <%= link_to "Edit Article", edit_article_path(@article), class: "btn btn-primary btn-lg btn-space" %>
        <%= link_to "Delete Article", article_path(@article), method: :delete, data: {confirm: "Are you sure to delete"}, class: 'btn btn-warning btn-lg btn-space' %>
    <% end %>
</article>

<hr>


<div class='col-md-12'>
 <%= form_for [@article, @comment ], :html => {class: "form-horizontal", role: "form"} do |f| %>
     <% if @comment.errors.any? %>
         <div class="panel panel-danger col-md-offset-1">
             <div class="panel-heading">
                 <h2 class="panel-title">
                 <%= pluralize(@comment.errors.count, "error") %>
                     prohibited this article from being saved:
                 </h2>
                 <div class="panel-body">
                     <ul>
                     <% @comment.errors.full_messages.each do |msg| %>
                         <li>
                             <%= msg %>
                         </li>
                     <% end %>
                     </ul>
                 </div>
             </div>
         </div>
     <% end %>
     <div class='form-group'>
         <div class='control-label col-md-2'>
             <%= f.label :body, 'New Comment' %>
         </div>
         <div class='col-md-10'>
             <%= f.text_area :body, rows: 10, class: 'form-control', placeholder: 'Your comment' %>
         </div>
     </div>
     <div class='form-group'>
         <div class='col-md-offset-2 col-md-10'>
             <%= f.submit "Add Comment", class: 'btn btn-primary btn-lg pull-right' %>
         </div>
     </div>
 <% end %>
</div>

<div class='col-md-12'>
    <header>
     <h2>Comments</h2>
    </header>
         <div class="col-md-10">
             <% if @article.comments.any? %>
                 <% @article.comments.persisted.each do |comment| %>
                     <div class="comment-body">
                         <%= comment.body %>
                     </div>
                     <div class="comment-time">
                         <%= time_ago_in_words(comment.created_at) %>
                         ago by <%= comment.user.email %>
                     </div>
 <hr>
                 <% end %>
             <% else %>
                 There are no comments to show.
             <% end %>
         </div>
</div

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BlogApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
<%= render 'shared/header' %>
<%= render 'shared/main' %>
<%= render 'shared/footer' %>
      

</body>
</html>

app/views/shared/_footer.html.erb
<div class='container-fluid'>
  <div class='row'>
      <div class='col-md-10 text-center'>
          <footer role='contentinfo'>
              <b><small>Copyright &copy; 2016 Madagascar</small></b>
          </footer>
      </div>
  </div>
</div>

app/views/shared/_header.html.erb
<header role='banner'>
    <nav class='navbar navbar-default navbar-fixed-top' role='navigation'>
      <div class='container-fluid'>
        <div class='navbar-header'>
          <button type='button' class='navbar-toggle' data-toggle='collapse' data-target='#navbar-collpase-1'>
            <span class='icon-bar'></span>
            <span class='icon-bar'></span>
            <span class='icon-bar'></span>
          </button>
          <%= link_to 'Blog_App', root_path, class: 'navbar-brand' %>
        </div>
        <div class='navbar-collapse collapse' id='navbar-collapse-1'>
          <ul class='nav navbar-nav'>
            <li class='active'><%= link_to 'Author', '#' %></li>
            <% if user_signed_in? %>
              <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
              <div class='pull-right'>
                <p class='navbar-text'>
                  Signed in as <%= "#{current_user.email}" %>
                </p>
              </div>
            <% end %>
            <li><%= link_to "Sign Up", new_user_registration_path %></li>
            <li><%= link_to "Sign In", new_user_session_path %></li>
          </ul>
        </div>
      </div>
    </nav>
</header>

app/views/shared/_main.html.erb
<div class='row'>
    <div class='col-md-10 col-md-offset-1'>
      <div class='col-md-8'>
        <% flash.each do |name, msg| %>
            <div class='alert-<%= "#{name}" %>'>
              <a href='#' class='close' data-dismiss='alert' &#215; ></a>
              <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
            </div>
        <% end %>  
          
        <%= yield %>
      </div>
      <div class='col-md-4'>
        <%= yield :sidebar %>
      </div>
    </div>
</div>